---
title: "Treadmill Polynomial Regression Model"
date: "10/2019"
output: 
  html_document:
      keep_md: true
      toc: true
      toc_float: true
      code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r datalibrary, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(pwr)
library(latex2exp)

## model objects

pr_model <- read_rds(path = "../data/polinomial_regression_model.rds")
pr_model_ms <- read_rds(path = "../data/polinomial_regression_model_metersecond.rds")

model_data <- read_csv("../data/training_model_data.csv" )
model_fixedspeeds_plot <- read_csv("../data/fixedspeeds_plot_data.csv" )

## training data

dat_model <- read_csv("../data/dat_model.csv")  

```

## Power Calculations



```{r}
powercalc <- pwr.f2.test(sig.level = .01, power = .99, f2 = 0.025, u = 6)
n_design <- ceiling(powercalc$v) + powercalc$u
```

Cohen's effect size calculation is $f2 = r^2 / (1  - r^2)$ where values around $0.02$ are used to be able to detect small effects.  We used $0.025$ or the ability to identify an $r^2$ slightly smaller than $0.025$. This resulted in a desired sample size of $n = `r n_design`$



## Modeling 

### Graphic of Our Model

```{r, fig.width=10, fig.height=7}
dat_model %>% 
  ggplot(aes(x = grade, y = actual_vo2kgml)) +
  geom_jitter(aes(color = speed_actual), height = 0, width = .25) +
  scale_color_viridis_c() +
  geom_line(data = model_fixedspeeds_plot, aes(y = .fitted, color  = speed_actual, group = factor(speed_actual))) +
  labs(title = "Development Group Data", x = "Grade (%)", 
       y = parse(text = TeX("C_w $(ml \\cdot kg^{-1} \\cdot min^{-1})$")), color = "Speed (mph)") +
  theme_bw()

cc <- pr_model$coefficients
eqn <- paste("Y =", paste(round(cc[1],5), paste(round(cc[-1],5), names(cc[-1]), sep=" * ", collapse=" + "), sep=" + "))

```

Here is the equation

`r eqn`


### Summary of Our Model

In miles per hour.

```{r}
broom::glance(pr_model) %>%
  knitr::kable(digits = 2)
```

```{r}
summary(pr_model) %>%
  tidy() %>%
  bind_cols(confint_tidy(pr_model)) %>%
  knitr::kable(digits = 5)
```



In meters per second

```{r}
broom::glance(pr_model_ms) %>%
  knitr::kable(digits = 2)
```

```{r}
summary(pr_model_ms) %>%
  tidy() %>%
  bind_cols(confint_tidy(pr_model)) %>%
  knitr::kable(digits = 5)
```
